Adding thread safety to the instantiation of the static HttpClients.
AzureAD/microsoft-authentication-library-for-dotnet pull request #2046
Opened 2020-09-17 14:49 UTC by trwalke

fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2034

2020-09-17 17:53 UTC, neha-bhargava commented
There is another implementation IMsalHttpClientFactory -- SimpleHttpClientFactory. I think we should implement it there too for consistency.

2020-09-17 17:56 UTC, neha-bhargava approved these changes
LGTM. Have added a suggestion in the comment.

2020-09-17 20:12 UTC, henrik-me commented on src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreHttpClientFactory.cs
>                  };
move inside the lock

2020-09-17 20:12 UTC, henrik-me commented on src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreHttpClientFactory.cs
> +        private static object s_lock = new object();
>object [](start = 23, length = 6)

mark readonly

2020-09-17 20:28 UTC, henrik-me commented on src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreHttpClientFactory.cs
> +        private static object s_lock = new object();
consider changing this to leverage the lazy construction we do elsewhere in the product. this will remove the need for the lock and the null check

2020-09-17 20:28 UTC, henrik-me requested changes
:clock1:

2020-09-17 20:28 UTC, henrik-me commented on src/client/Microsoft.Identity.Client/Platforms/netdesktop/Http/NetDesktopHttpClientFactory.cs
>          private static HttpClient s_httpClient;
same comments here

2020-09-22 17:54 UTC, henrik-me approved these changes
:shipit:

2020-09-22 18:29 UTC, henrik-me requested changes
:clock1:

2020-09-22 18:30 UTC, henrik-me commented
have a few things I would like to explore before merging this.

2020-09-22 18:30 UTC, henrik-me commented
+1

---
In reply to: [694399021](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2046#issuecomment-694399021) [](ancestors = 694399021)

2020-09-23 15:08 UTC, henrik-me commented
done. 

---
In reply to: [696901750](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2046#issuecomment-696901750) [](ancestors = 696901750)

2020-09-23 15:08 UTC, henrik-me approved these changes
:shipit:

2020-09-23 15:09 UTC, henrik-me commented
Travis can you pls. ensure you take a look at the suggestion provided here?

---
In reply to: [696901835](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2046#issuecomment-696901835) [](ancestors = 696901835,694399021)

2020-09-25 17:21 UTC, merged

2020-11-18 19:06 UTC, minune-msft commented on src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreHttpClientFactory.cs
> -        private static HttpClient s_httpClient;
For customers using this library before this fix, in scenarios where there are multiple instances of this, they will get "Properties can only be modified before sending the first request" HttpClient exception, that should be documented @trwalke