Bogavril/tc logs
AzureAD/microsoft-authentication-library-for-dotnet pull request #2717
Opened 2021-06-18 22:23 UTC by bgavrilMS

Fixes #2716 

**Changes proposed in this request**
Replace IEnumerable with IReadOnly list to avoid re-execution of filters 
Add more logging
Short-circuit some logs

**Testing**
perf testing

**Performance impact**
FindAccessTokenAsync for client_creds flow (before and after) does not show any meaningful difference.

current
|                     Method | TokenCacheSize |         Mean |        Error |       StdDev |
|--------------------------- |--------------- |-------------:|-------------:|-------------:|
| 'Different tenants - O(1)' |           1000 |     73.24 us |     1.372 us |     1.468 us |
|  'Different scopes - O(n)' |           1000 | 58,334.41 us | 1,104.858 us | 2,647.169 us |

|                     Method | TokenCacheSize |         Mean |        Error |       StdDev |       Median |
|--------------------------- |--------------- |-------------:|-------------:|-------------:|-------------:|
| 'Different tenants - O(1)' |           1000 |     78.49 us |     1.806 us |     5.123 us |     76.39 us |
|  'Different scopes - O(n)' |           1000 | 66,160.57 us | 1,284.855 us | 3,103.070 us | 66,411.26 us |

2021-06-18 22:52 UTC, jennyf19 approved these changes
:shipit:

2021-06-21 15:22 UTC, SameerK-MSFT approved these changes

2021-06-21 16:55 UTC, pmaytak requested changes
Some thoughts/questions:
- Have you tested with more than 1k tokens in the cache? Wonder if 1k is too small, maybe we need larger cache to see variance better.
- The perf test only tests ATs in the cache, right? These changes affect RTs too. Should we have a test for RT search flow too?
- Currently the perf test differentiates tokens by tenant and scope. Does this test real-world scenario? In order to get a more realistic test - how would the tokens in real-world app be different? My guess the environment, tenant (because of partitioning), token type are probably the same for all ATs. What about filtering by user assertions? (If the assertion doesn't match, we would hit all the filters?)

2021-06-22 08:05 UTC, pmaytak approved these changes

2021-06-22 08:23 UTC, merged