Add suggested web cache key for remove accounts
AzureAD/microsoft-authentication-library-for-dotnet pull request #2745
Opened 2021-07-06 19:50 UTC by neha-bhargava

Fixes # .
#2643 

**Changes proposed in this request**
Add suggested web cache key for remove accounts call.

**Testing**
Added unit test

**Performance impact**
None

2021-07-06 20:37 UTC, jmprieur approved these changes
LGTM.
Thanks @neha-bhargava 

@abhidnya13 : do you want to have a look as well?

2021-07-06 20:54 UTC, jennyf19 commented on tests/Microsoft.Identity.Test.Unit/CacheTests/SuggestedWebCacheKeyTests.cs
> +            const string tenantId = TestConstants.AadTenantId;
>tenantId [](http://example.com/codeflow?start=25&length=8)

nit: don't need a variable, as it's only used once.

2021-07-06 20:54 UTC, jennyf19 commented on tests/Microsoft.Identity.Test.Unit/CacheTests/SuggestedWebCacheKeyTests.cs
> +            var appTokenCache = new TokenCache(this._serviceBundle, isApplicationTokenCache: true);
>this [](http://example.com/codeflow?start=47&length=4)

nit: remove `this.` in all the places it's used.

2021-07-06 20:55 UTC, jennyf19 commented on tests/Microsoft.Identity.Test.Unit/CacheTests/SuggestedWebCacheKeyTests.cs
> +            var tenantAuthority = AuthorityInfo.FromAadAuthority(AzureCloudInstance.AzurePublic, tenant: tenantId, validateAuthority: false);
nit: no need for variable. pass it directly.

2021-07-06 20:56 UTC, jennyf19 commented on tests/Microsoft.Identity.Test.Unit/CacheTests/SuggestedWebCacheKeyTests.cs
> +            Assert.AreEqual(expectedKey, actualKey);
nit: no variable

2021-07-06 20:57 UTC, jennyf19 commented
can we have an integration test that uses it e2e and removes w/the cache key?

---
In reply to: [700360728](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2745#issuecomment-700360728) [](http://example.com/codeflow?ancestors=700360728,700360728)

2021-07-06 20:57 UTC, jennyf19 requested changes
:clock1:

2021-07-07 17:26 UTC, pmaytak approved these changes

2021-07-08 00:42 UTC, trwalke commented
> using Microsoft.Identity.Client;

This file is missing copywright info

---
Refers to: tests/Microsoft.Identity.Test.Unit/CacheTests/SuggestedWebCacheKeyTests.cs:2 in 5800554. [](commit_id = 5800554751339bd30e5f07e36ac151e306ab2565, deletion_comment = False)

2021-07-08 00:43 UTC, trwalke approved these changes
LGTM. Just need copyright info

2021-07-12 15:45 UTC, bgavrilMS commented
@jennyf19  - I updated MSAL's integration test around GetTokenByAuthCode with this. It's the only confidential client scenario where RemoveAccount can be used.

2021-07-12 16:49 UTC, jennyf19 approved these changes

2021-07-13 15:52 UTC, merged