Updated Readme
AzureAD/microsoft-authentication-library-for-dotnet pull request #2792
Opened 2021-07-22 23:35 UTC by SameerK-MSFT

**Changes proposed in this request**
Updated readme for the release

**Testing**
NA

**Performance impact**
NA

2021-07-23 03:41 UTC, jennyf19 requested changes
see comment in teams.

2021-07-23 09:38 UTC, jmprieur requested changes
This is not as customer focused as the previous changes for the previous versions, @SameerK-MSFT

2021-07-23 22:33 UTC, trwalke commented on changelog.txt
> +**AcquireTokenByIntegratedWindowsAuth against ADFS provides clearer error message** Error messages have been udpated. See issue [#2752](https://github.com/AzureAD/microsoft-authentication-library-for
```suggestion
**AcquireTokenByIntegratedWindowsAuth provides better error messages.** Error messages are now more actionable. See issue [#2752](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2752) 
```

2021-07-23 22:33 UTC, trwalke commented on changelog.txt
> +**Error messages in Integrated Windows Authentication are now clearer**. The following message related issues are fixed
Extra line

2021-07-23 22:37 UTC, trwalke commented on changelog.txt
> +**MSAL.NET would throw an ArgumentNullException if the provided CcsRoutingHint was null**, now authentication will proceed forward as providing the hint is for resiliency and should not prevent sign-
```suggestion
**MSAL.NET no longer throws ArgumentNullException when the parameters for WithCcsRoutingHint() are null.** Authentication will now proceed as if not hint was provided. See issue [#2755](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2755)
```

2021-07-23 22:42 UTC, trwalke commented on changelog.txt
> +**Instance discovery was being performed multiple times on non-public non-sovereign clouds.** You will get better performance as now it does discovery only if it is not in the cache. See issue [#2701
```suggestion
**Instance discovery was performed multiple times on non-public non-sovereign clouds.** MSAL provides improved performance as now it does discovery only when needed. See issue [#2701](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2701)
```

2021-07-23 23:06 UTC, trwalke commented on changelog.txt
> +**The mismtached authorities were throwing exceptions.** MSAL now does instance discovery to find the right match. See issue [#2736](https://github.com/AzureAD/microsoft-authentication-library-for-do
```suggestion
**MSAL no longer throws exceptions for mismatched authorities if they are known aliases.** MSAL now ensures authorities configured in the application and request are not aliased before throwing. See issue [#2736](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2736)
```

2021-07-26 16:48 UTC, SameerK-MSFT commented on changelog.txt
> +**Error messages in Integrated Windows Authentication are now clearer**. The following message related issues are fixed
Removed

2021-07-26 16:51 UTC, trwalke approved these changes
Thanks Sameer

2021-07-26 21:52 UTC, SameerK-MSFT commented
Readme has been updated. Let me know, if any further changes are required.

2021-07-26 21:53 UTC, merged