Added ParentWIndow to IsBrokeravailable
AzureAD/microsoft-authentication-library-for-dotnet pull request #3321
Opened 2022-05-12 21:52 UTC by SameerK-MSFT

Fixes # 3320

**Changes proposed in this request**
Added parent window parameter to the API

**Testing**
Manual testing using IntuneMAM iOS App

**Performance impact**
none

2022-05-13 07:43 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client/UI/CoreUIParent.cs
> +    public class CoreUIParent
please don't make this class public

2022-05-13 07:44 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
> +        public bool IsBrokerAvailable(CoreUIParent parentWindow = null)
No, please don't make this public.

2022-05-13 07:45 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
> +        public bool IsBrokerAvailable(CoreUIParent parentWindow = null)
Maybe we need a static helper `PCA.IsBrokerAvailable(authority, parent)` ?

2022-05-13 07:48 UTC, bgavrilMS requested changes
do not make coreuiparent public

2022-05-17 23:05 UTC, SameerK-MSFT commented
This is under discussion. Converting to draft

2022-06-28 11:37 UTC, bgavrilMS commented
@SameerK-MSFT - please fix this PR or close it.

2022-07-22 11:44 UTC, closed without merging