Hard deprecate AcquireTokenSilent(scopes, login_hint)
AzureAD/microsoft-authentication-library-for-dotnet pull request #3443
Opened 2022-07-01 18:37 UTC by MichelZ

Fixes #3403

2022-07-05 10:10 UTC, bgavrilMS approved these changes

2022-07-06 03:03 UTC, pmaytak requested changes
See comment in the issue.

2022-07-06 03:03 UTC, pmaytak commented on src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs
> +        AcquireTokenSilentParameterBuilder AcquireTokenSilent(IEnumerable<string> scopes, string loginHint);
I think this needs `new` and implementation in CCA class is not needed, similar to 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/7fff414e166d6e10eb68b44802830749a91841fb/src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs#L95-L97

2022-07-06 03:03 UTC, pmaytak commented on src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs
> +        /// Please use <see cref="IClientApplicationBase.AcquireTokenSilent(IEnumerable{string}, IAccount)"/>.
nit:
```suggestion
        /// In confidential client apps use <see cref="IClientApplicationBase.AcquireTokenSilent(IEnumerable{string}, IAccount)"/> instead.
```

2022-07-09 07:41 UTC, merged