Call AcquireTokenInteractively instead of SignInInteractively #3437
AzureAD/microsoft-authentication-library-for-dotnet pull request #3456
Opened 2022-07-06 21:45 UTC by gladjohn

Fixes #3437

**Changes proposed in this request**
If we know the account is in WAM and am able to rehydrate the account, we will now call AcquireTokenInteractively instead of SignInInteractively. We don’t want to show any unnecessary prompt to the user.

**Testing**
Dev App in different OSs

**Performance impact**
none, better user experience

2022-07-06 21:46 UTC, gladjohn commented
this needs to be updated based on my other PR (0.9.0 update)

2022-07-07 00:18 UTC, SameerK-MSFT approved these changes

2022-07-07 00:18 UTC, SameerK-MSFT commented on src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
> +
nit: extra line

2022-07-07 00:18 UTC, SameerK-MSFT commented on src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
> +                            if (result.IsSuccess)
Line #118 to #127 are same as Line 92-101. Optimize please

2022-07-07 00:41 UTC, neha-bhargava approved these changes

2022-07-07 07:54 UTC, pmaytak approved these changes

2022-07-07 07:54 UTC, pmaytak commented on src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
> +                if (string.IsNullOrEmpty(authenticationRequestParameters.LoginHint))
If `LoginHint` is provided, then `Account` on Line 101 will never be null?

2022-07-07 07:54 UTC, pmaytak commented on src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
> +        public static MsalTokenResponse AcquireTokenFromBroker(NativeInterop.AuthResult authResult,
Rename to something like HandleResponse, ProcessResponse, ParseResponse.
nit: put first param on new line.

2022-07-07 10:49 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
> +                if (string.IsNullOrEmpty(authenticationRequestParameters.LoginHint))
shouldn't this use "loginHint" from line 80?

2022-07-07 10:53 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
> +                    authenticationRequestParameters.Account.HomeAccountId.ObjectId,
I think this logic needs to be cleaned up a bit. It should more like: 

1. If an Account object is present and if that object has an ID and Object Id THEN do `AcquireTokenInteractivelyAsync`
2. If a loginHint is present (as defined at line 80), then do SignInInteractivelyAsync

Remember that we don't force app developers to use our Account objects. THey only have an interface called IAccount (in hinghsight, this was a mistake). I have seen a LOT of ppl creating their own Account objects which ignore the ID.

2022-07-07 10:55 UTC, bgavrilMS requested changes
Account obj might be corrupted, you need to do more defensive programming.

2022-07-11 17:28 UTC, gladjohn commented
> Account obj might be corrupted, you need to do more defensive programming.

handled now

2022-07-11 18:08 UTC, pmaytak approved these changes

2022-07-11 18:37 UTC, gladjohn commented on src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
> +                msalTokenResponse = WamAdapters.ParseRuntimeResponse(authResult, authenticationRequestParameters, logger);
if parsing fails then we throw `MsalRuntimeException`

2022-07-11 19:13 UTC, merged