Change the logger.Always messages to logger.Info as it creates too mu…
AzureAD/microsoft-authentication-library-for-dotnet pull request #3684
Opened 2022-09-19 03:09 UTC by jennyf19

…ch noise for services. Many are already taking the metrics from the authResult, so they may not want it always again in the logs.

Fixes #
#3683 

In .NET Core, the mapping Always to Critical is not going to work, because they appear as Critical (see the linked item for details). Service owners will not want this level appearing in their logs. Based on the logs, they can all be added an information and not always.

2022-09-19 03:21 UTC, jmprieur approved these changes
LGTM
Thanks @jennyf19 

@pmaytak @trwalke @neha-bhargava @gladjohn @sameerkapps : why do you want to log always this information (given it would be translated in Critical and displayed in Red in .NET Core)

2022-09-19 13:45 UTC, bgavrilMS approved these changes

2022-09-19 13:47 UTC, bgavrilMS commented
> LGTM Thanks @jennyf19
> 
> @pmaytak @trwalke @neha-bhargava @gladjohn @sameerkapps : why do you want to log always this information (given it would be translated in Critical and displayed in Red in .NET Core)

Maybe we should not translate MSAL's `Always` to ASP.NET Core's `Critical` ? Always are log messages we always want to log. They are not indicative of an error. The purpose is to avoid asking customer who already has logging enabled to change log verbosity.

2022-09-19 13:58 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
> +            requestParams.RequestContext.Logger.Info($"[FindRefreshTokenAsync] Discovered {refreshTokens.Count} refresh tokens in cache using key: {requestKey}. ");
These 2 are quite useful.

2022-09-19 13:59 UTC, bgavrilMS requested changes
Isn't https://github.com/AzureAD/microsoft-identity-web/pull/1891 enough to fix the issue? The "log always" concept was copied from Azure Identity, it's just that it should not translate to ASP.NET Core's "critical"

https://learn.microsoft.com/en-us/dotnet/azure/sdk/logging#map-to-aspnet-core-logging

2022-09-22 13:33 UTC, bgavrilMS commented
Closing this one, the information there is pretty useful. Solution to the root bug was added in Id.Web

2022-09-22 13:33 UTC, closed without merging