Move the MSAL desktop cache extension + tests
AzureAD/microsoft-authentication-library-for-dotnet pull request #4089
Opened 2023-04-17 15:36 UTC by bgavrilMS

Currently no build changes.

Fixes #

**Changes proposed in this request**

**Testing**

**Performance impact**

**Documentation**
- [ ] All relevant documentation is updated.

2023-08-10 07:42 UTC, pmaytak commented
Is this actually ready for review or more work needs to be done? What changes were made - is it just moving the the cache extensions code under the cache extensions folder (I see some other unrelated changes?)?

What build related changes need to be done? I think we have the release/ci/pr builds. Would we use OneBranch for this also?

2023-08-10 13:30 UTC, bgavrilMS commented
> Is this actually ready for review or more work needs to be done? What changes were made - is it just moving the the cache extensions code under the cache extensions folder (I see some other unrelated changes?)?
> 
> What build related changes need to be done? I think we have the release/ci/pr builds. Would we use OneBranch for this also?

You are right, there are some build changes remaining. Moving back to draft.

2023-08-15 13:29 UTC, bgavrilMS commented
@pmaytak - do you remember how to fix the test error "n exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'." ?

2023-08-16 01:18 UTC, pmaytak commented
> @pmaytak - do you remember how to fix the test error "n exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'." ?

I think it was just updating to the latest version of those dependencies?
This PR maybe? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4036

2023-08-18 17:19 UTC, gladjohn approved these changes

2023-08-22 21:00 UTC, pmaytak commented on LibsAndSamples.sln
> -		build\template-build-ios-automation.yaml = build\template-build-ios-automation.yaml
Seems unrelated to cache changes, move to separate PR?

2023-08-23 06:15 UTC, trwalke commented on LibsAndSamples.sln
> +		build\template-OneBranch-libsandsamples.yaml = build\template-OneBranch-libsandsamples.yaml
Im assuming this branch has the latest changes right?
Is this a merge error? These files should be there.

2023-08-23 06:18 UTC, trwalke commented on tests/Microsoft.Identity.Test.Unit/PublicApiTests/TelemetryClientTests.cs
> +    [DeploymentItem(@"Resources\valid_cert.pfx")]
Yeah, sometimes I ran into this issue locally. this should resolve it

2023-08-23 06:19 UTC, trwalke requested changes
Missing files for OneBranch Build

2023-08-24 20:54 UTC, bgavrilMS commented
@trwalke - what files are missing?

2023-08-24 20:59 UTC, bgavrilMS commented on LibsAndSamples.sln
> +		build\template-OneBranch-libsandsamples.yaml = build\template-OneBranch-libsandsamples.yaml
I now added all 3 OneBranch files - please take a look


build\template-OneBranch-CI-libsandsamples.yaml = build\template-OneBranch-CI-libsandsamples.yaml
build\template-OneBranch-Release-libsandsamples.yaml = build\template-OneBranch-Release-libsandsamples.yaml
build\template-OneBranch-releasebuild-netonly.yaml = build\template-OneBranch-releasebuild-netonly.yaml

2023-08-25 19:09 UTC, trwalke approved these changes

2023-08-28 11:03 UTC, merged