Updating error messages for non RSA certificates messages
AzureAD/microsoft-authentication-library-for-dotnet pull request #4443
Opened 2023-11-30 23:04 UTC by trwalke

Fixes #
fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4407

**Changes proposed in this request**
Updating error messages for non RSA certificates messages

**Testing**
Added unit test

**Performance impact**

**Documentation**
- [ ] All relevant documentation is updated.

2023-11-30 23:09 UTC, trwalke commented on src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
> +            if (!certificate.PublicKey.Oid.FriendlyName.Equals(Constants.RsaFriendlyName))
not sure if `Oid.FriendlyName` is the best way to do this. looking into if there is abetter way to check for RSA

2023-12-01 13:07 UTC, bgavrilMS commented on tests/Microsoft.Identity.Test.Unit/CryptographyTests.cs
> +
nit: assert that the test cert type is ECD

2023-12-01 13:38 UTC, bgavrilMS commented on tests/Microsoft.Identity.Test.Unit/CryptographyTests.cs
> +        public static X509Certificate2 GenerateSelfSignedCertificate()
nit: There is already a CertificateHelper in MSAL, can you use that?

2023-12-01 13:38 UTC, bgavrilMS requested changes
Improve error messages, account for missing Key as well.

2023-12-04 17:48 UTC, trwalke commented on src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
> +            if (rsa == null)
Oh yes, I missed the fact that the key can be missing. I used the `Oid.FriendlyName` in my previous commit but then I read somewhere on stack overflow that not all certificates will have the `FriendlyName` field populated so I changed the approach. I will do some more digging to see if we can rely on the `FriendlyName`.

2023-12-05 00:55 UTC, pmaytak commented on src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
> +            if (rsa == null)
Yea, would probably be better to check on a type, if possible, rather than a string FriendlyName?

2023-12-05 00:55 UTC, pmaytak commented on tests/Microsoft.Identity.Test.Unit/CryptographyTests.cs
> +        public void SignWithNonRsaCertificate()
For test naming, good practice is to add what the expected result is, so it's easier to see at a glance.
```suggestion
        public void SignWithNonRsaCertificate_ThrowsException()
```

2023-12-05 06:20 UTC, trwalke commented on src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
> +            if (rsa == null)
So, I did some more digging on this and it looks like we cannot guarantee that the `FriendlyName` field will be populated or even contain the word `RSA`. Here is a list of the known friendly names for .net core. As you can see, not all of them have `RSA` but it is not clear if those configs still use RSA.
https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Security.Cryptography.Encoding/src/Internal/Cryptography/OidLookup.cs#L113


Also, [we already have a check for a certificate without a private key](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0eecb41515a816eb3860f656aae575042935fc1e/src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs#L121) so this code will never have to deal with that scenario. We can rely upon the fact `GetRSAPrivateKey` will return null if the key is not of type RSA.

2023-12-07 11:56 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
> +            if (rsa == null)
Discussed that it's not practical to check the friendly name. However, if RSAKey == null, we can put the OID Friendly Name in the error message,.

2023-12-08 15:05 UTC, bgavrilMS approved these changes

2023-12-15 15:17 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
> +        public const string CryptoNet45 =
bad rebase? This has been deleted.

2023-12-15 15:17 UTC, bgavrilMS approved these changes

2023-12-26 19:48 UTC, gladjohn approved these changes

2023-12-26 19:48 UTC, gladjohn commented on src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
> +        public const string CryptoNet45 =
```suggestion
        public const string CryptoNet45 = "Error: Certificate signing failed. Please check the inner exception for detailed information.\n" +
    "- Possible Cause: The app may be built against .NET Desktop 4.6 or lower.\n" +
    "- Suggested Actions: \n" +
    "   1. Target a higher version of .NET Desktop (4.6.2 or above).\n" +
    "   2. Use a different type of certificate (non-CNG).\n" +
    "   3. Consider signing your own assertion. For more details, visit: https://aka.ms/msal-net-signed-assertion";

```

2023-12-26 19:48 UTC, gladjohn commented on src/client/Microsoft.Identity.Client/Internal/Constants.cs
> +        public const string RsaFriendlyName = "RSA";
is this used?

2023-12-27 03:44 UTC, trwalke commented on src/client/Microsoft.Identity.Client/Internal/Constants.cs
> +        public const string RsaFriendlyName = "RSA";
not needed

2023-12-27 19:21 UTC, pmaytak approved these changes

2024-01-03 18:50 UTC, merged