replace combo of where and FirstOrDefault with only FirstOrDefault
AzureAD/microsoft-authentication-library-for-dotnet pull request #4509
Opened 2024-01-14 00:54 UTC by SimonCropp

less code and faster since it it only on lambda allocation

2024-01-17 11:59 UTC, bgavrilMS approved these changes

2024-01-18 07:03 UTC, pmaytak requested changes

2024-01-18 07:03 UTC, pmaytak commented on tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs
> +                    var x5c = jsonToken.Header.FirstOrDefault(header => header.Key == "x5c");
Should be moved up to the previous location.

2024-01-18 19:07 UTC, pmaytak approved these changes

2024-01-19 18:18 UTC, merged