Bogavril/xamarin removal
AzureAD/microsoft-authentication-library-for-dotnet pull request #4706
Opened 2024-04-10 15:19 UTC by bgavrilMS

Remove Xamarin!!

2024-04-16 03:55 UTC, pmaytak requested changes
Left some suggestions.

2024-04-16 03:55 UTC, pmaytak commented on src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
> -    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == '$(TargetFrameworkNet6Mac)'">14.0</SupportedOSPlatformVersion>
There are other references to `TargetFrameworkNet6Mac` in this file and in platform_and_feature_flags.props that can be removed.

2024-04-16 03:55 UTC, pmaytak commented on src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
> +  <ItemGroup>
Remove this? Redundant? Should be already included by default.

2024-04-16 03:55 UTC, pmaytak commented on Directory.Packages.props
>      <PackageVersion Include="Xamarin.AndroidX.Browser" Version="1.4.0" PrivateAssets="All" />
Should this be removed too? We add it in net6-android, but I didn't see anywhere where we use this namespace in code.

2024-04-16 03:56 UTC, pmaytak commented
@bgavrilMS Does this branch build for you locally? Fails to build for me and installing MAUI workloads also fails (can't find some dependency in the feeds....). :(

2024-04-16 14:43 UTC, bgavrilMS commented
> @bgavrilMS Does this branch build for you locally? Fails to build for me and installing MAUI workloads also fails (can't find some dependency in the feeds....). :(

No, it fails for me too due to old .NET SDK. I ended up using net7-android / net7-ios to verify the build etc. 

I was thinking of bumping to net7-*** althoghter, but it's not trivial - there are some APIs which are now obsolete and I don't have a full Android / iOS setup to test. We can revisit this if it causes build issues on the lab.

2024-04-18 05:36 UTC, pmaytak approved these changes
:shipit:

2024-04-18 07:27 UTC, trwalke reviewed
No Longer needed?
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/4a8c4ddae8a36d811d4ebf55af30d0feba03577d/LibsAndSamples.sln#L138

2024-04-18 07:29 UTC, trwalke reviewed
I dont think we still need LibsMacOS.sln

2024-04-18 07:31 UTC, trwalke reviewed
No longer need template-build-android-automation.yaml

2024-04-18 16:42 UTC, neha-bhargava commented on build/platform_and_feature_flags.props
> -  <PropertyGroup Condition="'$(TargetFramework)' == '$(TargetFrameworkIos)' Or '$(TargetFramework)' == '$(TargetFrameworkNet6Ios)' Or '$(TargetFramework)' == '$(TargetFrameworkNet6Mac)'">
Does `TargetFrameworkNet6Mac` also needs to be removed?

2024-04-18 16:49 UTC, gladjohn approved these changes
looks good. Can we also delete the Automation framework / subscription we used to have to run Android and IOS tests? Do not remember the name now just making sure we do the clean up of that if not required anymore

2024-04-18 16:49 UTC, gladjohn commented on Directory.Packages.props
> +    <MsalInternalVersion>4.61.0</MsalInternalVersion>
undo?

2024-04-18 16:52 UTC, bgavrilMS commented
> looks good. Can we also delete the Automation framework / subscription we used to have to run Android and IOS tests? Do not remember the name now just making sure we do the clean up of that if not required anymore

For sure. I don't know where it is though... @trwalke ?

2024-04-18 20:50 UTC, trwalke approved these changes

2024-04-18 21:03 UTC, neha-bhargava approved these changes

2024-04-19 00:10 UTC, pmaytak approved these changes

2024-04-19 09:22 UTC, merged