Expose client capabilities in AssertionRequestOptions for MSI FIC scenarios
AzureAD/microsoft-authentication-library-for-dotnet pull request #4972
Opened 2024-10-22 18:27 UTC by gladjohn

Fixes #4948

**Changes proposed in this request**
Updated AssertionRequestOptions to handle client capabilities for MSI Federated Identity Credential (FIC) scenarios, ensuring that higher-level SDKs can pass capabilities to MSAL.

**Testing**
unit tests

**Performance impact**
n/a

**Documentation**
- [ ] All relevant documentation is updated.

2024-10-22 22:57 UTC, neha-bhargava approved these changes

2024-10-24 06:52 UTC, trwalke approved these changes

2024-10-24 12:01 UTC, bgavrilMS commented on src/client/Microsoft.Identity.Client/AppConfig/AssertionRequestOptions.cs
> +        public IEnumerable<string> ClientCapabilities { get; set; }
Aren't going to set these?

2024-10-24 12:03 UTC, bgavrilMS requested changes
You also need to set them.

2024-11-19 19:55 UTC, gladjohn commented
close this and add this as part of the token revocation pr

2024-11-19 19:55 UTC, closed without merging